### ISSUE TITLE
Fail to capture the default_host and etc.

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#146]
### Terraform Version
```
$ tf version
Terraform v0.11.13
+ provider.fastly v0.5.0
```

### Problem
I have created a service in Fastly UI, and I want to import it into tf land. 

But looks like the diff missing to capture the settings entirely.
```
settings:
  general.default_host: <bucket>.s3.amazonaws.com
  general.default_pci: 0
  general.default_ttl: 3600
  general.stale_if_error: false
  general.stale_if_error_ttl: 43200
```

I can see it in the tf config, but it is just not in the diff part.

### How to reproduce
- Create a new service (guide in here, https://docs.fastly.com/guides/integrations/amazon-s3)
- Import into tf land (`terraform import fastly_service_v1.demo xxxxxxxxxxxxxxxxxxxx`)
- Run `terraform plan`
